apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: java-ecommerce-app-deployment
spec:
  selector:
    matchLabels:
      app: java-ecommerce-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: java-ecommerce-app
    spec:
      containers:
        - name: java-ecommerce-app
          image: jayeshrajput/java-ecommerce-app:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: java-ecommerce-app-svc
spec:
  selector:
    app: java-ecommerce-app
  ports:
    - protocol: "TCP"
      port: 8070 # The port that the service is running on in the cluster
      targetPort: 8070 # The port exposed by the service
  type: NodePort # type of the service.
